### ISSUE TITLE
compose.queued messages

### ISSUE THREAD

**Issue by pypingou** [CentOS-PaaS-SIG/ci-pipeline#212]
When looking at the messages in https://apps.stg.fedoraproject.org/datagrepper/raw?category=ci (scroll down to get more) I see compose.running and compose.complete but no compose.queued is this expected?

**Comment by scoheb** [comment]
From what I can tell from the pipeline...since we are now using a single pipeline, certain stages will not get queued like the previous legacy pipelines.
In other words, once **ci.pipeline.package.complete** is sent, we send **ci.pipeline.compose.running** right away since it was not queued but merely the next stage to execute.

I will let Ari add to this...

**Comment by pypingou** [comment]
Cool, make things simpler :)

Could we adjust the documentation/README for this?

**Comment by scoheb** [comment]
@arilivigni let's discuss when you are back.

**Comment by arilivigni** [comment]
I updated the documentation to remove this queued for composes.  These will NOT be published.
